# Generated by Django 4.0.4 on 2022-05-16 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_test', '0004_alter_car_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_test.collection'),
        ),
    ]
