# Generated by Django 4.0.4 on 2022-05-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_test', '0005_alter_car_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='collection',
        ),
        migrations.AddField(
            model_name='car',
            name='collection',
            field=models.ManyToManyField(to='rest_test.collection'),
        ),
    ]
